# Generated by Django 3.2.7 on 2023-01-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(max_length=255, unique=True, upload_to='Profiles'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='categories'),
        ),
    ]
