# Generated by Django 3.2.7 on 2023-01-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230117_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='profiles/default-user.png', null=True, upload_to=''),
        ),
    ]
